### ISSUE TITLE
Small error in Question 2 part d

### ISSUE THREAD

**Issue by dorukkilitcioglu** [Bogazici-CMPE548-Spring2016/Cmpe548-Assignment2#1]
The assignment states that "_... the chain has approximately reached the stationary distribution
when the total variation distance between π and A<sup>t</sup>π_". Shouldn't the second π be π<sub>0</sub> (as in the "_distance between π and A<sup>t</sup>π<sub>0</sub>_")?

**Comment by ilkerg** [comment]
That's correct, thank you.
Fixed and pushed the updated pdf.
You can [sync](https://help.github.com/articles/syncing-a-fork/) your repositories to obtain the updated version.
